# Generated by Django 3.0.5 on 2020-07-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(verbose_name='DOB')),
                ('qualification', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('specialization', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'studwent_data',
            },
        ),
    ]
