# Generated by Django 3.0.7 on 2020-07-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='static/blog/images/no_image.jpeg', max_length=255, upload_to='static/blog/images/'),
        ),
    ]
